# Generated by Django 3.1.2 on 2022-10-05 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=254)),
                ('description', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='EUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('lastname', models.CharField(max_length=254)),
                ('firstname', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=254)),
                ('confirm_password', models.CharField(max_length=254)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuizTaken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnings.category')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnings.euser')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=254)),
                ('correct_answer', models.CharField(max_length=254)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnings.category')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(max_length=254)),
                ('is_correct', models.BooleanField()),
                ('quiz_taken_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnings.quiztaken')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnings.euser')),
                ('word_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnings.word')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_id', to='learnings.euser')),
                ('following_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_id', to='learnings.euser')),
            ],
        ),
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_a', models.CharField(blank=True, max_length=254, null=True)),
                ('choice_b', models.CharField(blank=True, max_length=254, null=True)),
                ('choice_c', models.CharField(blank=True, max_length=254, null=True)),
                ('choice_d', models.CharField(blank=True, max_length=254, null=True)),
                ('word_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnings.word')),
            ],
        ),
    ]
