# Generated by Django 4.1.2 on 2022-10-19 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("learnings", "0002_alter_category_options_alter_choices_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("activity_description", models.CharField(max_length=254)),
                (
                    "follow_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learnings.follow",
                    ),
                ),
                (
                    "quiz_taken_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learnings.quiztaken",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learnings.euser",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "UserActivityLog",
            },
        ),
    ]
