# Generated by Django 4.1.2 on 2022-10-19 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("learnings", "0003_useractivitylog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useractivitylog",
            name="follow_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="learnings.follow",
            ),
        ),
        migrations.AlterField(
            model_name="useractivitylog",
            name="quiz_taken_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="learnings.quiztaken",
            ),
        ),
    ]
