# Generated by Django 4.1.2 on 2022-10-20 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("learnings", "0004_alter_useractivitylog_follow_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useractivitylog",
            name="follow_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="follow_username",
                to="learnings.euser",
            ),
        ),
    ]
